<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/SN_web_lightmode.png" width="300"> 
</center>

# Assignment: Exploratory Data Analysis with SQL
Estimated time needed: 60 minutes


# Introduction
Using this R notebook you will perform exploratory data analysis using SQL queries with the RSQLite R package. You will be graded on the accuracy of your results as well as the content of your SQL queries.

### Establish your SQL Lite connection

#### Install RSQLite package
The RSQlite  package needs to be installed in your notebook. Let’s load the RSQLite package by clicking on the following cell and executing it (Shift+Enter):

In [1]:
install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", repos = NULL, type = "source", dependencies = TRUE)

Warning message in install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", :
“installation of package ‘/tmp/Rtmpnmpgdc/downloaded_packages/RSQLite_0.10.0.tar.gz’ had non-zero exit status”

#### Restart Kernel

After installing the RSQLite package, it is necessary to restart R Kernel. Click **Kernel** > **Restart Kernel** from the main menu. This will register the newly installed packages. Now proceed to load the RSQLite package.

#### Load RSQLite
Load the 'RSQLite' library, and use the 'dbConnect( )' function as you did in the previous labs to establish the connection to your SQLite database.  
You are now ready to start running SQL queries using the RSQLite library as you did in Course 3.

In [6]:
library("RSQLite")
library(readr)

In [7]:
# provide your solution here to connect db
conn <- dbConnect(RSQLite::SQLite(), "RDSProject.db")

Download the following csv files:

*   [WORLD_CITIES](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/world_cities.csv)

*   [BIKE_SHARING_SYSTEMS](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/bike_sharing_systems.csv)

*   [CITIES_WEATHER_FORECAST](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/cities_weather_forecast.csv)

*   [SEOUL_BIKE_SHARING](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/seoul_bike_sharing.csv)

and load the csv's  into 4 tables as mentioned below
* SEOUL_BIKE_SHARING

* CITIES_WEATHER_FORECAST

* BIKE_SHARING_SYSTEMS 

*  WORLD_CITIES

> Hint : Use the read_csv() function and dbWriteTable() functions

In [8]:
world_cities <- read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/world_cities.csv")
bike_sharing_systems <- read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/bike_sharing_systems.csv")
cities_weather_forecast <- read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/cities_weather_forecast.csv")
seoul_bike_sharing <- read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/seoul_bike_sharing.csv")

dbWriteTable(conn, "SEOUL_BIKE_SHARING", seoul_bike_sharing, overwrite = TRUE)
dbWriteTable(conn, "CITIES_WEATHER_FORECAST", cities_weather_forecast, overwrite = TRUE)
dbWriteTable(conn, "BIKE_SHARING_SYSTEMS", bike_sharing_systems, overwrite = TRUE)
dbWriteTable(conn, "WORLD_CITIES", world_cities, overwrite = TRUE)

dbListTables(conn)

Rows: 26569 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): CITY, CITY_ASCII, COUNTRY, ISO2, ISO3, ADMIN_NAME, CAPITAL
dbl (4): LAT, LNG, POPULATION, ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 480 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): COUNTRY, CITY, SYSTEM
dbl (1): BICYCLES

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 160 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): CITY, WEATHER, SEASON
dbl  (8): VISIBILITY, TEMP, TEMP_MIN, TEMP_MAX, PRESSURE, HUMIDITY, WIND_SPE...
dttm (1): FORECAST_DATETIME

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8465 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): DATE, SEASONS, HOLIDAY, FUNCTIONING_DAY
dbl (10): RENTED_BIKE_COUNT, HOUR, TEMPERATURE, HUMIDITY, WIND_SPEED, VISIBI...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] "BIKE_SHARING_SYSTEMS"    "CITIES_WEATHER_FORECAST"
[3] "SEOUL_BIKE_SHARING"      "WORLD_CITIES"


## Task 1 - Record Count
#### Determine how many records are in the seoul_bike_sharing dataset.

### Solution 1

In [10]:
dbGetQuery(conn, "SELECT COUNT(*) Record_Count FROM SEOUL_BIKE_SHARING")

  Record_Count
1 8465

## Task 2 - Operational Hours
#### Determine how many hours had non-zero rented bike count.

### Solution 2

In [13]:
dbGetQuery(conn, "SELECT COUNT(HOUR) COUNT_OF_HOURS, SUM(HOUR) SUM_OF_HOURS FROM SEOUL_BIKE_SHARING WHERE RENTED_BIKE_COUNT > 0")

  COUNT_OF_HOURS SUM_OF_HOURS
1 8465           97407

## Task 3 - Weather Outlook
#### Query the the weather forecast for Seoul over the next 3 hours.
Recall that the records in the CITIES_WEATHER_FORECAST dataset are 3 hours apart, so we just need the first record from the query.

### Solution 3

In [27]:
SQL_QUERY <- "SELECT * FROM CITIES_WEATHER_FORECAST WHERE CITY = 'Seoul' ORDER BY FORECAST_DATETIME LIMIT 1"
dbGetQuery(conn, SQL_QUERY)

  CITY  WEATHER VISIBILITY TEMP  TEMP_MIN TEMP_MAX PRESSURE HUMIDITY WIND_SPEED
1 Seoul Clear   10000      12.32 10.91    12.32    1015     50       2.18
  WIND_DEG SEASON FORECAST_DATETIME
1 248      Spring 1618574400

## Task 4 - Seasons
#### Find which seasons are included in the seoul bike sharing dataset.

### Solution 4

In [35]:
SQL_QUERY <- "SELECT DISTINCT SEASONS FROM SEOUL_BIKE_SHARING"
dbGetQuery(conn, SQL_QUERY)

  SEASONS
1 Winter
2 Spring
3 Summer
4 Autumn

## Task 5 - Date Range
#### Find the first and last dates in the Seoul Bike Sharing dataset.

### Solution 5

In [37]:

SQL_QUERY <- "SELECT 
    MIN(DATE(substr(DATE, 7, 4) || '-' || substr(DATE, 4, 2) || '-' || substr(DATE, 1, 2))) FIRST_DATE, 
    MAX(DATE(substr(DATE, 7, 4) || '-' || substr(DATE, 4, 2) || '-' || substr(DATE, 1, 2))) LAST_DATE 
    FROM SEOUL_BIKE_SHARING"

dbGetQuery(conn, SQL_QUERY)

  FIRST_DATE LAST_DATE
1 2017-12-01 2018-11-30

## Task 6 - Subquery - 'all-time high'
#### determine which date and hour had the most bike rentals.

### Solution 6

In [38]:

SQL_QUERY <- "SELECT DATE, HOUR, RENTED_BIKE_COUNT FROM SEOUL_BIKE_SHARING
    WHERE RENTED_BIKE_COUNT = (SELECT MAX(RENTED_BIKE_COUNT) FROM SEOUL_BIKE_SHARING)"

dbGetQuery(conn, SQL_QUERY)

  DATE       HOUR RENTED_BIKE_COUNT
1 19/06/2018 18   3556

## Task 7 - Hourly popularity and temperature by season
#### Determine the average hourly temperature and the average number of bike rentals per hour over each season. List the top ten results by average bike count.

### Solution 7

In [40]:
SQL_QUERY <- "WITH SEASONALAVGS AS (SELECT SEASONS, HOUR, AVG(TEMPERATURE) AVG_TEMP, 
    AVG(RENTED_BIKE_COUNT) AVG_RENTED_BIKE_COUNT FROM SEOUL_BIKE_SHARING GROUP BY SEASONS, HOUR)
    SELECT SEASONS, HOUR, AVG_TEMP, AVG_RENTED_BIKE_COUNT FROM SEASONALAVGS 
    ORDER BY AVG_RENTED_BIKE_COUNT DESC LIMIT 10;"

dbGetQuery(conn, SQL_QUERY)

   SEASONS HOUR AVG_TEMP AVG_RENTED_BIKE_COUNT
1  Summer  18   29.38791 2135.141
2  Autumn  18   16.03185 1983.333
3  Summer  19   28.27378 1889.250
4  Summer  20   27.06630 1801.924
5  Summer  21   26.27826 1754.065
6  Spring  18   15.97222 1689.311
7  Summer  22   25.69891 1567.870
8  Autumn  17   17.27778 1562.877
9  Summer  17   30.07691 1526.293
10 Autumn  19   15.06346 1515.568

## Task 8 - Rental Seasonality
#### Find the average hourly bike count during each season. 
Also include the minimum, maximum, and standard deviation of the hourly bike count for each season. 

> Hint : Use the SQRT(AVG(col*col) - AVG(col)*AVG(col) ) function where col refers to your column name for finding the standard deviation

### Solution 8

In [41]:
SQL_QUERY <- "SELECT SEASONS, AVG(RENTED_BIKE_COUNT) AVG_BIKE_COUNT, MIN(RENTED_BIKE_COUNT) MIN_BIKE_COUNT,
    MAX(RENTED_BIKE_COUNT) MAX_BIKE_COUNT, SQRT(AVG(RENTED_BIKE_COUNT * RENTED_BIKE_COUNT) - AVG(RENTED_BIKE_COUNT) * 
        AVG(RENTED_BIKE_COUNT)) STDDEV_BIKE_COUNT FROM SEOUL_BIKE_SHARING GROUP BY SEASONS;"

dbGetQuery(conn, SQL_QUERY)

  SEASONS AVG_BIKE_COUNT MIN_BIKE_COUNT MAX_BIKE_COUNT STDDEV_BIKE_COUNT
1 Autumn   924.1105      2              3298           617.3885
2 Spring   746.2542      2              3251           618.5247
3 Summer  1034.0734      9              3556           690.0884
4 Winter   225.5412      3               937           150.3374

Let's explore a bit and see what might be the most significant contributing factors in terms of the provided data.

## Task 9 - Weather Seasonality
#### Consider the weather over each season. On average, what were the TEMPERATURE, HUMIDITY, WIND_SPEED, VISIBILITY, DEW_POINT_TEMPERATURE, SOLAR_RADIATION, RAINFALL, and SNOWFALL per season?
Include the average bike count as well , and rank the results by average bike count so you can see if it is correlated with the weather at all.

### Solution 9

In [42]:
SQL_QUERY <- "
SELECT
    SEASONS,
    AVG(TEMPERATURE) AS AVG_TEMPERATURE,
    AVG(HUMIDITY) AS AVG_HUMIDITY,
    AVG(WIND_SPEED) AS AVG_WIND_SPEED,
    AVG(VISIBILITY) AS AVG_VISIBILITY,
    AVG(DEW_POINT_TEMPERATURE) AS AVG_DEW_POINT_TEMP,
    AVG(SOLAR_RADIATION) AS AVG_SOLAR_RADIATION,
    AVG(RAINFALL) AS AVG_RAINFALL,
    AVG(SNOWFALL) AS AVG_SNOWFALL,
    AVG(RENTED_BIKE_COUNT) AS AVG_BIKE_COUNT
FROM
    SEOUL_BIKE_SHARING
GROUP BY
    SEASONS
ORDER BY
    AVG_BIKE_COUNT DESC;"

dbGetQuery(conn, SQL_QUERY)

  SEASONS AVG_TEMPERATURE AVG_HUMIDITY AVG_WIND_SPEED AVG_VISIBILITY
1 Summer  26.587711       64.98143     1.609420       1501.745
2 Autumn  13.821580       59.04491     1.492101       1558.174
3 Spring  13.021685       58.75833     1.857778       1240.912
4 Winter  -2.540463       49.74491     1.922685       1445.987
  AVG_DEW_POINT_TEMP AVG_SOLAR_RADIATION AVG_RAINFALL AVG_SNOWFALL
1  18.750136         0.7612545           0.25348732   0.00000000
2   5.150594         0.5227827           0.11765617   0.06350026
3   4.091389         0.6803009           0.18694444   0.00000000
4 -12.416667         0.2981806           0.03282407   0.24750000
  AVG_BIKE_COUNT
1 1034.0734
2  924.1105
3  746.2542
4  225.5412

## Task 10 - Total Bike Count and City Info for Seoul
#### Use an implicit join across the WORLD_CITIES and the BIKE_SHARING_SYSTEMS tables to determine the total number of bikes avaialble in Seoul, plus the following city information about Seoul: CITY, COUNTRY, LAT, LON, POPULATION, in a single view.
Notice that in this case, the CITY column will work for the WORLD_CITIES table, but in general you would have to use the CITY_ASCII column.

### Solution 10

In [49]:
SQL_QUERY <- "
SELECT
    W.CITY,
    W.COUNTRY,
    W.LAT,
    W.LNG,
    W.POPULATION,
    SUM(B.BICYCLES) AS TOTAL_BICYCLES
FROM
    WORLD_CITIES W,
    BIKE_SHARING_SYSTEMS B
WHERE
    W.CITY = 'Seoul' AND
    W.CITY = B.CITY
GROUP BY
    W.CITY,
    W.COUNTRY,
    W.LAT,
    W.LNG,
    W.POPULATION;
"
dbGetQuery(conn, SQL_QUERY)

  CITY  COUNTRY      LAT     LNG POPULATION TOTAL_BICYCLES
1 Seoul Korea, South 37.5833 127 21794000   20000

## Task 11 - Find all city names and coordinates with comparable bike scale to Seoul's bike sharing system
#### Find all cities with total bike counts between 15000 and 20000. Return the city and country names, plus the coordinates (LAT, LNG), population, and number of bicycles for each city.
Later we will ask you to visualize these similar cities on leaflet, with some weather data.

### Solution 11

In [50]:
SQL_QUERY <- "
SELECT
    W.CITY,
    W.COUNTRY,
    W.LAT,
    W.LNG,
    W.POPULATION,
    SUM(B.BICYCLES) AS TOTAL_BICYCLES
FROM
    WORLD_CITIES W
JOIN
    BIKE_SHARING_SYSTEMS B
ON
    W.CITY = B.CITY
GROUP BY
    W.CITY,
    W.COUNTRY,
    W.LAT,
    W.LNG,
    W.POPULATION
HAVING
    SUM(B.BICYCLES) BETWEEN 15000 AND 20000;
"
dbGetQuery(conn, SQL_QUERY)

  CITY     COUNTRY       LAT     LNG      POPULATION TOTAL_BICYCLES
1 Beijing  China         39.9050 116.3914 19433000   16000
2 Milan    Italy         45.4669   9.1900  1351562   17000
3 Milan    United States 35.9126 -88.7554     7201   17000
4 Milan    United States 42.0816 -83.6853     7778   17000
5 Ningbo   China         29.8750 121.5492  7639000   15000
6 Seoul    Korea, South  37.5833 127.0000 21794000   20000
7 Shanghai China         31.1667 121.4667 22120000   19165
8 Weifang  China         36.7167 119.1000  9373000   20000
9 Zhuzhou  China         27.8407 113.1469  3855609   20000

In [ ]:
close(conn)

## Author(s)

<h4> Jeff Grossman </h4>
<h4> Lakshmi Holla </h4>


## Other Contributor(s)

<h4>  Malika Singla </h4>

<!--## Change log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                 |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 2022-03-03        | 1.0     |Lakshmi Holla  | Created lab using sqlite3          |-->

## <h3 align="center"> © IBM Corporation 2022. All rights reserved. <h3/>